# Generated by Django 2.0 on 2018-09-30 10:05

import article.models
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('-created_date',), 'verbose_name': 'Məqalə', 'verbose_name_plural': 'Məqalələr'},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=article.models.upload_to, verbose_name='Başlıq Şəkli'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=ckeditor.fields.RichTextField(max_length=5000, verbose_name='Yazı'),
        ),
    ]
