# Generated by Django 2.0 on 2018-10-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181013_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Taq', 'verbose_name_plural': 'Taqlar'},
        ),
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default='default', editable=False, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='article.Tag', verbose_name='Taqlar'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Taq'),
        ),
    ]
