# Generated by Django 2.0 on 2018-10-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20181014_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='default', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
